### ISSUE TITLE
Homebrew package

### ISSUE THREAD

**Issue by lucasmichot** [orieg/php-judy#16]
Hello @orieg , 
I am one of the maintainer of homebrew-php repo.
php*-judy PECL extension will soon be merged.
https://github.com/josegonzalez/homebrew-php/pull/826

Feel free to upgrade you installation instructions for Mac OSX Homebrew users and create PR for new php-judy versions.

Happy coding,

Lucas

**Comment by orieg** [comment]
Late response but updated documentation: https://github.com/orieg/php-judy#install-with-homebrew
