### ISSUE TITLE
Open for maintenance?

### ISSUE THREAD

**Issue by negram** [orieg/php-judy#26]
Hi there,

I can see, there were no updates for quite a while, that's why I'm asking.
We have some updates for the extension, including a port to PHP 8.x. Would you be open to accepting them? Or maybe transfer the maintenance to someone?

**Comment by orieg** [comment]
I'm sorry for not getting back to you sooner. Since PHP 7, arrays performance improved quite a bit. IMO there is now limited value in using PHP Judy arrays. Happy to take a PR tho.

**Comment by negram** [comment]
Hi @orieg, thank you for getting back. I will need to initiate the formal approval in our company (not hard but may take time).
I will get back to you then.

Agree, that performance-wise, PHP and Judy have some sort of parity but in memory consumption, Judy is still better, especially for storing sets.
